export const breedList = [
  "Labrador Retriever",
  "Beagle",
  "Border Collies",
  "Boxer",
  "Corgi",
  "Dachshund",
  "English Springer Spaniel",
  "French Bulldog",
  "German Shepherd Dog",
  "Japanese Spitz",
  "Siberian Huskies",
  "Shih Tzu",
  "Standard Poodle",
  "Yorkshire Terrier",
  "Xoloitzcuintli",
];
